IF DB_ID(N'Db_Count') IS NULL
BEGIN
    CREATE DATABASE [Db_Count];
END
GO
USE [Db_Count];
GO
IF OBJECT_ID(N'dbo.Log_Server', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Log_Server (ApplicationId INT NULL, SubId INT NULL, EnterTime DATETIME NULL, Online INT NULL, Reg INT NULL);
END
GO
IF OBJECT_ID(N'dbo.Log_DropItem', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Log_DropItem (ApplicationId INT NULL, SubId INT NULL, LineId INT NULL, UserId INT NULL, ItemId INT NULL, TemplateID INT NULL, DropId INT NULL, DropData INT NULL, EnterTime DATETIME NULL);
END
GO
IF OBJECT_ID(N'dbo.Log_Item', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Log_Item (ApplicationId INT NULL, SubId INT NULL, LineId INT NULL, EnterTime DATETIME NULL, UserId INT NULL, Operation INT NULL, ItemName NVARCHAR(255) NULL, ItemID INT NULL, AddItem NVARCHAR(MAX) NULL, BeginProperty NVARCHAR(MAX) NULL, EndProperty NVARCHAR(MAX) NULL, Result INT NULL);
END
GO
IF OBJECT_ID(N'dbo.Log_Fight', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Log_Fight (ApplicationId INT NULL, SubId INT NULL, LineId INT NULL, RoomId INT NULL, RoomType INT NULL, FightType INT NULL, ChangeTeam INT NULL, PlayBegin DATETIME NULL, PlayEnd DATETIME NULL, UserCount INT NULL, MapId INT NULL, TeamA NVARCHAR(MAX) NULL, TeamB NVARCHAR(MAX) NULL, PlayResult NVARCHAR(MAX) NULL, WinTeam INT NULL, Detail NVARCHAR(MAX) NULL);
END
GO
IF OBJECT_ID(N'dbo.Log_Money', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.Log_Money (ApplicationId INT NULL, SubId INT NULL, LineId INT NULL, MastType INT NULL, SonType INT NULL, UserId INT NULL, EnterTime DATETIME NULL, Moneys INT NULL, Gold INT NULL, GiftToken INT NULL, Offer INT NULL, OtherPay NVARCHAR(MAX) NULL, GoodId NVARCHAR(MAX) NULL, ShopId NVARCHAR(MAX) NULL, Datas NVARCHAR(MAX) NULL);
END
GO
